fixing deployment issues
1. [...nextauth]/route type error problem need to have other file in utils for npm builds to works
2. userPlaylist authoptions directory changed
3. Mood Chart page small fixes regarding
    Cannot read properties of undefined (reading 'tracks')
    TypeError: Cannot read properties of undefined (reading 'labels')
   adding error return if data is not avaiable or not valid
4. playlist error undefined track url
   new problem with showing tracks
5. prisma index.ts  small fixes needed and changing directory in [...nextauth] for prisma to use our index.ts file not the from prisma client "@prisma/client"